name: location
description: A Flutter plugin for location with Callbacks.
version: 1.3.4
author: Guillaume Bernos
homepage: https://github.com/Lyokone/flutterlocation

flutter:
  plugin:
    androidPackage: com.lyokone.location
    pluginClass: LocationPlugin

environment:
  sdk: '>=1.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
